решение задачи про удаление строк из таблицы
js-tasks-ru/jsbasic-20210420_evstigney pull request #7
Opened 2021-05-18 22:10 UTC by evstigney

2021-05-18 22:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-20 11:54 UTC, SinimaWath requested changes

2021-05-20 11:54 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this._card.querySelector('.card__button').addEventListener('click', this._onButtonClick);
Почему потписка на событие в getter?

По своей сути, в get функция, не должно быть, такой неявной логики

2021-05-20 11:54 UTC, SinimaWath commented on package.json
> +  }
Не стоит изменять package.json

2021-05-20 12:22 UTC, evstigney commented on package.json
> +  }
Я не изменяла. Обновила npm и все.

2021-05-20 12:28 UTC, evstigney commented on 6-module/2-task/index.js
> +    this._card.querySelector('.card__button').addEventListener('click', this._onButtonClick);
Я, безусловно, могу отдельно для подписки на событие написать метод. Просто зачем? Все равно нужен геттер. Почему в нем нельзя писать подписку?

2021-05-22 00:15 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    this._card.querySelector('.card__button').addEventListener('click', this._onButtonClick);
В этом случае, на каждое обращение к свойству, создается новая подписка.
Но зачем если это можно сделать в конструкторе. И тогда у тебя будет одна подписка на весь экземпляр класса

2021-05-22 00:16 UTC, SinimaWath approved these changes

2021-05-22 00:17 UTC, merged